# -- Site Configuration --
# https://gohugo.io/getting-started/configuration/

baseURL = "https://letsphi.com/"
theme = "blowfish"
defaultContentLanguage = "en"

enableRobotsTXT = true
summaryLength = 30
timeout = "600s" # first build processes many post images

buildDrafts = false
buildFuture = false

[pagination]
  pagerSize = 100

[imaging]
  anchor = "Center"

[taxonomies]
  tag = "tags"
  category = "categories"

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

[outputs]
  home = ["HTML", "RSS", "JSON"]

[related]
  threshold = 0
  toLower = false

  [[related.indices]]
    name = "tags"
    weight = 100
